url:
  generate:
    preset: 500000

hazelcast:
  members:
    - "localhost:5701"
    - "localhost:5702"
    - "localhost:5703"
  redoOperation: true
  connectionTimeout: 0
  connectionAttempts: 5

---

spring.profiles: docker

hazelcast:
  members:
    - "hazelcast-service-1:5701"
    - "hazelcast-service-2:5701"
    - "hazelcast-service-3:5701"
